config/routes.rb
Quantum::Application.routes.draw do
 
  resources :comments, only: [:index, :create, :edit, :update, :destroy]
  resources :blogs do
    put 'like', on: :member
  end
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resource :new_leads, only: [:create]
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root to: 'static_pages#home'
  match 'contact' => 'contact_us#new', :as => 'contact', :via => :get
  match 'contact' => 'contact_us#create', :as => 'contact', :via => :post
  match 'about', to: 'static_pages#about'
  match 'sitemap' => 'sitemaps#index', defaults: { format: "xml" }

  
  

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: [:slugged, :history]

  attr_accessible :content, :title, :visible

  has_many :comments, dependent: :destroy

  validates :content, presence: true
  validates :title, presence: true
  validates :slug, presence: true

  default_scope order: 'blogs.created_at DESC'

  def previous_post
  	self.class.first(conditions: ["id < ?", id], order: "id desc")
  end

  def next_post
  	self.class.last(conditions: ["id > ?", id], order: "id asc")
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_filter :require_signed_in_user, only: [:new, :create, :edit, :update, :destroy]
  before_filter :require_admin_user, only: [:edit, :update, :destroy]
  after_filter  :increment_view_count, only: :show

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs =  Blog.where(visible:true).paginate(page: params[:page], per_page: 8)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blogs }
    end
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blog = Blog.find(params[:id])
    if request.path != blog_path(@blog)
      redirect_to @blog, status: :moved_permanently
    end

    #cookies[:blog_id] = {value: params[:id]}
    #@comment = Comment.new
    #@comments = @blog.comments.paginate(page: params[:page], per_page: 10)
    
  end

  # GET /blogs/new
  # GET /blogs/new.json
  def new
    @blog = Blog.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blog }
    end
  end

  # GET /blogs/1/edit
  def edit
    @blog = Blog.find(params[:id])
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(params[:blog])

    if @blog.save
      redirect_to @blog, notice: 'Blog was successfully created.'   
    else
      render action: "new"
    end
  end

  # PUT /blogs/1
  # PUT /blogs/1.json
  def update
    @blog = Blog.find(params[:id])

    if @blog.update_attributes(params[:blog])
      redirect_to @blog, notice: 'Blog was successfully updated.'
    else
      render action: "edit"
      render json: @blog.errors, status: :unprocessable_entity
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy

    redirect_to blogs_url
  end

  def like
    @blog=Blog.find(params[:id])
    @blog.likes += 1
    if @blog.save
      head :created, location: like_blog_path(@blog)
    else
      head :internal_server_error, location: like_blog_path(@blog)
    end
  end

end

app/helpers/blogs_helper.rb
module BlogsHelper
	def markdown(text)
		options = [:hard_wrap, :filter_html, :autolink,
					:no_intraemphasis, :fenced_code, :gh_blockcode]
		renderer = Redcarpet::Render::HTML.new(hard_wrap:true, prettify:true)
		markdown = Redcarpet::Markdown.new(renderer, no_intraemphasis:true, fenced_code_blocks:true, 
				disable_indented_code_blocks:true, underline:true, tables:true, strikethrough:true, autolink:true,
				lax_spacing:true, superscript:true, highlight:true, quote:true, footnotes:true)
		markdown.render(text).html_safe
	end

	def increment_view_count
		@blog.views += 1
		@blog.save
	end
end

app/views/blogs/_created_at.erb
<span class="blog date"> 
    <span class="month"><%= blog.created_at.strftime("%b")%></span> 
    <span class="day"><%= blog.created_at.strftime("%-d")%></span> 
    <span class="year"><%= blog.created_at.strftime("%Y")%></span> 
 </span> 

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <fieldset>
	  <div class="control-group">
	  	<%= f.label :title %>
	  	<%= f.text_field :title, class:"span12" %>
	  </div>
	  <div class="control-group">
	    <%= f.label :content %>
	    <%= f.text_area :content, rows: 50, class: "span12" %>
	  </div>
	  <div class="control-group">
	  	<%= f.label :visible, "Visible?" %>
	  	<%= f.check_box :visible %>
	  </div>
	  <div class="control-group">
	    <%= f.submit "Save", class: "btn btn-primary btn-large pull-right"%>
	    <%= link_to 'Blogs', blogs_path, class: "btn btn-primary btn-large" %>
	  </div>
  </fieldset>
<% end %>

app/views/blogs/edit.html.erb
<%provide :title, @blog.title %>

<h1>Editing blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<%provide :title, "Rails Fever Blog"%>
<%provide :description, 'Latest blog posts'%>
<%provide :keywords, 'blog, rails fever, railsfever, rails, ruby, capistrano, capistrano 3, symmetric encryption' %>

<div class="container">
  <%= will_paginate @blogs, class: 'pagination pagination-right no-margin pagination-mini', 
      previous_label: '<', next_label: '>', renderer: 'FeverRenderer' %>
</div>
<div class="hero-unit">
    <div class="container">
      <h2>Blog</h2>
    </div>
    <!--close container--> 
  </div>
  <!--close hero-unit-->
  
  <div class="container clearfix" id="main-content"> 
    <!--begin main content-->
    <div class="row-fluid"> 
      <!--begin row-fluid-->
      <div class="span12 blog-summary primary-column"> 
        
        <% @blogs.each do |blog| %>
          <!-- begin entry-post -->
          <article class="entry-post">
            <header class="entry-header">
              <h3 class="entry-title"> <%=link_to blog.title, blog %> </h3>
              <div class="byline">
                <i class="fa fa-bell-o"></i> <abbr class="published" title="<%= blog.created_at %>"> <%= blog.created_at.strftime("%B %-d, %Y") %></abbr> &nbsp;&nbsp;
                <i class="fa fa-eye"></i> <abbr><%=pluralize(blog.views, 'View')%></abbr> &nbsp;&nbsp;
                <i class="fa fa-heart"></i> <abbr><%=pluralize(blog.likes, 'Like')%></abbr> &nbsp;&nbsp;
                <a href="<%= blog_path(blog.friendly_id) %>#disqus_thread">Comments</a>        
              </div>
            </header>
            <!--end entry-header --> 
            
            <!--begin loop of entry-posts for summary page-->
            
            <div class="entry-content">
              <%= markdown truncate(blog.content, length: 800, seperator: ' ' ) %>
              <p class="more right">
                <%= link_to blog, class: 'btn btn-primary' do %>
                  Read More &rarr;
                <% end %> 
                <% if admin? %>
                  <%= link_to 'Edit', edit_blog_path(blog), class: 'btn btn-primary' %> 
                  <%= link_to 'Destroy', blog, 
                        method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary' %>
                <% end %>
              </p>
            </div>
            <!-- close entry-content -->
            
            <footer class="entry-footer"> 
              <%= render partial: "created_at", locals: {blog: blog} %>
            </footer>
            <!--end entry-footer--> 
          </article>
          <!-- end entry-post --> 
        <% end %>
        
        <!--end loop of entry-posts for summary page-->
        
        <%= will_paginate @blogs, class: 'pagination pagination-right no-margin pagination-mini', 
      previous_label: '<', next_label: '>', renderer: 'FeverRenderer' %>
      </div>
      <!-- close .span9 . primary-column .blog-summary-->
    </div>
    <!--close row-fluid--> 

    <%= debug(params) if Rails.env.development? %>
  </div>
  <!--close .container id="main-content" --> 

  <!--  for displaying comment count  -->
    <script type="text/javascript">
      /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
      var disqus_shortname = 'railsfever'; // required: replace example with your forum shortname

      /* * * DON'T EDIT BELOW THIS LINE * * */
      (function () {
          var s = document.createElement('script'); s.async = true;
          s.type = 'text/javascript';
          s.src = '//' + disqus_shortname + '.disqus.com/count.js';
          (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
      }());
    </script>

app/views/blogs/new.html.erb
<%provide :title, "New Blog"%>

<div class="container">
	<h1>New Blog</h1>

	<%= render 'form' %>

</div>

app/views/blogs/show.html.erb
<%provide :title, @blog.title %>

<p id="notice"><%= notice %></p>

<div class="container clearfix" id="main-content">
		<div class="row-fluid">
			<section class="call-to-action center clearfix">
				<div class="message">
					<h3>Need an experienced Rails developer?</h3>
					<p>I am working hard right now to make my clients super happy! You could be next.</p>
				</div>
				<%= render 'layouts/shared/hire_me_button' %>
			</section>
		</div>
		<!--close row-fluid-->

		<!--begin main content-->
		<div class="row-fluid blog"> 
			<!--begin row-fluid-->
			<div class="span12 blog-detail primary-column"> 
				<!--begin primary-column-->
				<article class="entry-post">
					<header class="entry-header">
						<h1><%= @blog.title %></h1>
						<div class="byline">
							<i class="fa fa-bell-o"></i> 
							<abbr class="published" title="<%= @blog.created_at %>"> <%= @blog.created_at.strftime("%B %-d, %Y") %></abbr> &nbsp;&nbsp; 
			                <i class="fa fa-eye"></i> <abbr><%=pluralize(@blog.views, 'View')%></abbr> &nbsp;&nbsp;
			                <i class="fa fa-heart"></i> <abbr><%=pluralize(@blog.likes, 'Like')%></abbr> &nbsp;&nbsp;
			                <%= link_to "#disqus_thread" do %>
			                  <!--i class="icon-comments-alt"></i-->
			                <% end %>
						</div>
						
						<!--add this share buttons for mobile viewers-->
						<div class="addthis_toolbox addthis_16x16_style"> 
							<a class="addthis_button_preferred_2"></a> 
							<a class="addthis_button_preferred_3"></a> 
							<a class="addthis_button_preferred_7"></a> 
							<a class="addthis_button_preferred_6"></a> 
							<a class="addthis_button_preferred_10"></a> 
							<a class="addthis_button_preferred_4"></a> 
							<a class="addthis_button_compact"></a> 
						</div>
					</header>
					<!--end entry-header-->
					
					<div class="entry-content">		
						<%= markdown @blog.content %>	
					</div>
					<!--end entry-content-->
					<footer class="entry-footer"> 	
						<%= render partial: "created_at", locals: {blog: @blog} %>
						<!-- add this share buttons for desktop and larger screens -->
						<div class="addthis_toolbox addthis_16x16_style"> 
							<a class="addthis_button_preferred_2"></a> 
							<a class="addthis_button_preferred_3"></a> 
							<a class="addthis_button_preferred_7"></a> 
							<a class="addthis_button_preferred_6"></a> 
							<a class="addthis_button_preferred_10"></a> 
							<a class="addthis_button_preferred_4"></a> 
							<a class="addthis_button_compact"></a> 
						</div>
						<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=xa-50b7b03737b7ccb9">
						</script> 
						<!-- AddThis Button END --> 
					</footer>
					<!--end entry-footer--> 

						
					<p class="more right">
						<a id='like-button' class='btn btn-primary' data-blog="<%=@blog.id%>" >
							<i class='icon-heart'></i>
							Like
						</a>
						<% if admin? %>
							<%= link_to 'Edit', edit_blog_path(@blog), 
								class: 'btn btn-primary' %>
						<% end %>
					</p>
						
					
				</article>
				<!--end entry-post -->
				
				<div class="entry-pagination">
					<ul class="pager">
						<% if @blog.previous_post %>
							<li>	
								<%= link_to @blog.previous_post do %>
									&larr; Older
								<% end %>
							</li>
						<% end %>
						<% if @blog.next_post %>
							<li>	
								<%= link_to @blog.next_post do %>
									Newer &rarr;
								<% end %>
							</li>
						<% end %>						
					</ul>
					<!--close pager--> 
				</div>
				<!--end entry-pagination-->
				

				<div id="disqus_thread"></div>
			</div>
		</div>
		<%= debug(params) if Rails.env.development? %>
<div>

	
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'railsfever'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

<!--  for displaying comment count  -->
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'railsfever'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function () {
        var s = document.createElement('script'); s.async = true;
        s.type = 'text/javascript';
        s.src = '//' + disqus_shortname + '.disqus.com/count.js';
        (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
    }());
</script>
     