config/routes.rb
Quantum::Application.routes.draw do
 
  resources :comments, only: [:index, :create, :edit, :update, :destroy]
  resources :blogs do
    put 'like', on: :member
  end
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resource :new_leads, only: [:create]
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root to: 'static_pages#home'
  match 'contact' => 'contact_us#new', :as => 'contact', :via => :get
  match 'contact' => 'contact_us#create', :as => 'contact', :via => :post
  match 'about', to: 'static_pages#about'
  match 'sitemap' => 'sitemaps#index', defaults: { format: "xml" }

  
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content
  belongs_to :blog
  validates :blog_id, presence: true
  validates :content, presence: true
  default_scope order: 'comments.created_at DESC'
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :require_signed_in_user, only: [ :index, :edit, :update, :destroy]
  before_filter :require_admin_user, only: [:index, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  
  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    #@comment = Comment.new(params[:comment])
    blog_id = cookies[:blog_id]
    @blog = Blog.find(blog_id)
    @comment = @blog.comments.build(content: params[:comment][:content])

    if @comment.save
      redirect_to blog_path(blog_id)
    else
      flash[:error] = 'Comment was not saved'
      redirect_to blog_path(blog_id)
    end
    

  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment.blog}
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<li>
  <span class="content"><%= comment.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(comment.created_at) %> ago.
  </span>
</li>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'shared/comment_form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<%provide :title, "Legacy Comments" %>

<h1>Listing comments</h1>

<table>
  <tr>
    <th>Content</th>
    <th>Blog</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.content %></td>
    <td><%= comment.blog_id %></td>
    
    <% if admin? %>
      <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
      <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>
</table>