config/routes.rb
Quantum::Application.routes.draw do
 
  resources :comments, only: [:index, :create, :edit, :update, :destroy]
  resources :blogs do
    put 'like', on: :member
  end
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resource :new_leads, only: [:create]
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root to: 'static_pages#home'
  match 'contact' => 'contact_us#new', :as => 'contact', :via => :get
  match 'contact' => 'contact_us#create', :as => 'contact', :via => :post
  match 'about', to: 'static_pages#about'
  match 'sitemap' => 'sitemaps#index', defaults: { format: "xml" }

  
  

end

app/models/new_lead.rb
class NewLead

	include ActiveModel::Validations
	include ActiveModel::Conversion
	extend ActiveModel::Naming

	attr_accessor :name, :email

	validates :name, :email, presence: true
   
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, format: { with: VALID_EMAIL_REGEX }


	def initialize( attributes = {} )
		attributes.each do |name, value|
			send("#{name}=", value)
		end
	end

	def persisted?
		false
	end

end

app/controllers/new_leads_controller.rb
class NewLeadsController < ApplicationController

	def create
		@new_lead = NewLead.new(params[:new_lead])
		respond_to do |format|
			if @new_lead.valid?
				NewLeadMailer.new_message(@new_lead).deliver
				flash.now[:notice] = 'Thank you, we will be in touch shortly'
				#format.js {} 
				#flash.now[:notice] = "Thank you, we will be in touch shortly"
			else
				flash.now[:error] = "Please fill in all fields"
				format.js {}
			end
		end
	end

end

app/views/new_leads/_form.html.erb
<%= form_for @new_lead, remote: true, :url => new_leads_path do |form| %>
  <%= render 'shared/error_messages', object: form.object %>
  <div id=flash-message> </div>
  <fieldset>
    <div class="control-group">
      <%= form.label :name, 'Name' %>
      <%= form.text_field :name, class: "span10" %>
    </div>

    <div class="control-group">
      <%= form.label :email, 'Email' %>
      <%= form.email_field :email, class: "span10" %>
    </div>

    <%= form.button "Send", class: "btn btn-primary btn-large" %>
  </fieldset>
<% end %>

app/views/new_leads/create.js.erb
$('new-leads-form').html('<%= escape_javascript render("new_leads/form") %>');