config/routes.rb
Quantum::Application.routes.draw do
 
  resources :comments, only: [:index, :create, :edit, :update, :destroy]
  resources :blogs do
    put 'like', on: :member
  end
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resource :new_leads, only: [:create]
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root to: 'static_pages#home'
  match 'contact' => 'contact_us#new', :as => 'contact', :via => :get
  match 'contact' => 'contact_us#create', :as => 'contact', :via => :post
  match 'about', to: 'static_pages#about'
  match 'sitemap' => 'sitemaps#index', defaults: { format: "xml" }

  
  

end

app/views/layouts/_footer.html.erb
<!--begin footer -->
<footer id="footer" class="clearfix">
<div class="container"><!--footer container-->
	
	<div class="row-fluid">
		<div class="span12">
			
		</div>
		<!--close span12--> 
	</div>
	<!--close row-fluid-->
	
	<div class="row-fluid">
		<div class="span4">
			<!--section>
				<h4>Status</h4>
					<p>
						Actively seeking new clients
					</p>	
			</section-->
			<!--close section--> 

			<section>
				<h4>Contact Me</h4>
				<p>Hire me today to start your project!</p>
				<p>Rails Fever LLC<br>
					Philadelphia Pennsylvania USA<br>
					<strong>phone:</strong> <a href="tel:267 999 9253" class="tele">267 999 WALE</a><br>
					<strong>email:</strong> <a href="mailto:contact@railsfever.com">contact@railsfever.com</a> <br>
				</p>
			</section>
			<!--close section-->
			
			

			<section>
				<div class="user clearfix visuallyhidden"> 
					<a href=<%= signin_path %> ></a> 
				</div>
			</section>
			<!--close section -->
		</div>
		<!-- close .span4 --> 
		
		
		
		<!--section containing blog posts-->
		<div class="span6">
			<section>
				
				<h4>Read my recent Blog posts</h4>
				<ul class="footerPosts">
					<% Blog.where(visible:true).limit(6).each do |b| %>
							<li> 
								<%= link_to( 
									truncate(b.title, length: 60, seperator: ' '), 
									blog_path(b.friendly_id)) 
								%> 
								<span class="meta">
									<%= b.created_at.strftime("%B %-d, %Y") 
									%>
								</span>
							</li>
					<% end %>
				</ul>
			</section>
		</div>
		<!-- close .span4 --> 

		<!--section containing newsletter signup and recent images-->
		<!--div class="span4">
			<section>
				<h4>Recent News</h4>
				<p>
					<a href="http://ankane.github.io/chartkick/">
						Beautiful Javascript charts with one line of Ruby
					<a>
				</p>
				<p>
					<a href="https://deadmanssnitch.com/">
						Ensure your periodic tasks are actually running
					<a>
				</p>
				<p>
					<a href="http://railsgirlssummerofcode.org/campaign/">
						Help Rails Girls students get into open source projects
					<a>
				</p>
				<p>
					<a href="http://37signals.com/svn/posts/3432-why-i-loved-building-basecamp-for-iphone-in-rubymotion">
						Building Basecamp for iPhone in RubyMotion
					<a>
				</p>
				<p>
					<a href="http://blog.programmableweb.com/2013/05/30/heroku-launches-platform-api/">
						Heroku Launches Platform API
					<a>
				</p>
				<p>
					<a href="http://venturebeat.com/2013/05/09/white-house-drafts-official-open-data-policy-of-the-united-states-on-github/#lUqdMOwEPFljQFrq.99">
						White House drafts official ODP of the U.S on GitHub
					<a>
				</p>
				<p>
					<a href="http://venturebeat.com/2013/06/07/at-our-current-rate-of-progress-ipv6-will-be-fully-implemented-on-may-10-2048/#9qUOetFzq1BJTq52.99">
						IPv6 will be fully implemented on May 10, 2148
					<a>
				</p>
			</section>
			<!--close section-->
		<!--/div-->
		<!-- close .span4 --> 
	</div>
	<!-- close .row-fluid--> 
</div>
<!-- close footer .container--> 

<!--change this to your stuff-->
<section class="footerCredits">
	<div class="container">
		<ul class="clearfix">
			<li>© <%=Time.now.year%> Rails Fever LLC. All rights reserved.</li>
			<li><a href="<%= sitemap_path %>">Site Map</a></li>
		</ul>
	</div>
	<!--footerCredits container--> 
</section>
<!--close section--> 
</footer>
<!--/.footer--> 

<span class="backToTop"><a href="#top">back to top</a></span>

app/views/layouts/_google_analytics.html.erb
<!-- FOR GOOGLE ANALYTICS -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-39283511-1', 'auto');
  ga('require', 'displayfeatures');
  ga('send', 'pageview');
</script>

app/views/layouts/_google_surveys.html.erb
<script async="" defer="" src="//survey.g.doubleclick.net/async_survey?site=h32xmj6kyp3vsvrv7mpvnv3uhm"></script>

app/views/layouts/_header.html.erb
<!-- begin accesibility skip to nav skip content -->
<ul class="visuallyhidden" id="top">
	<li><a href="#nav" title="Skip to navigation" accesskey="n">Skip to navigation</a></li>
	<li><a href="#page" title="Skip to content" accesskey="c">Skip to content</a></li>
</ul>
<!-- end /.visuallyhidden accesibility--> 

<!-- mobile navigation trigger-->
<h5 class="mobile_nav"><a href="javascript:void(0)">&nbsp;<span></span></a></h5>
<!--end mobile navigation trigger-->



<!-- begin .header-->
<header class="header  clearfix"> 
	<%= image_tag src="print-logo.png", class:'print logo', alt:'Rails Fever' %>
	<div class="container"> 
		
		<!-- begin #main_menu -->
		<nav id="main_menu" class="ddsmoothmenu">
			<ul class="accordmobile">
				<li><a href="<%= root_path %>">Home</a></li>
				<li id="blog" class="parent"> <a href=<%=blogs_path %> > Blog <i></i> </a>
					<ul>
						<% Blog.where(visible:true).limit(5).each do |b| %>
							<li> <%= link_to( 
									truncate(b.title, length: 24, seperator: ' '), 
									blog_path(b.friendly_id)) %> </li>
						<% end %>
					</ul>
				</li>
				<li><a href="<%= about_path %>">About</a></li>
				<li><a href="<%= contact_path %>">Contact</a></li>
				<% if signed_in? %>
					<li class="parent">
						<a href="#">Admin <i></i> </a>
						<ul>
	        				<li><%= link_to 'New Blog', new_blog_path %></li>
	        				<li><%= link_to "view my account", current_user %></li>
	       					<li><%= link_to "edit my account", 
	             				edit_user_path(current_user) %>
	             			</li>
	        				<li><%= link_to "view all users", users_path %></li>
	        				<% if admin? %>
	        					<li><%= link_to "view all comments", comments_path %></li>
	        				<% end %>
	        				<li> <%= link_to 'Log Out', signout_path, 
	        				method: 'delete' %> </li> 
		      				
						</ul>
					</li>
				<% end %>
			</ul>
		</nav>
		<!-- close / #main_menu --> 
		
		<!-- begin #logo -->
		<div id="logo"> <a href="<%= root_path %>"> <%= image_tag src="trans.gif", alt:'' %><em>Rails Fever</em><!-- ie7 support--></a> </div>
		<!-- end #logo --> 
		
	</div>
	<!-- close / .container--> 
</header>
<!-- close /.header --> 

app/views/layouts/application.html.erb
  <!DOCTYPE html>
  <html>
  <head>
  <title>Rails Fever | <%= yield(:title) %> </title>
  <meta name="author" content="Akinwale Wale Olaleye">
  <meta name="description" content="<%= yield(:description) %>">
  <meta name="keywords" content="<%= yield(:keywords) %>">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
  <meta name="<author" content="akinwale olaleye">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

   <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->

  <!--[if lt IE 9]>
          <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  </head>
  <body class="index-flex-light">

  <%= render 'layouts/header' %>
  <!-- RENDER FLASH MESSAGES -->
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"> <%= value %> </div>
  <% end %>

  <div id="page"> 
    <%= yield %>

    <%= render 'layouts/footer' %>

    <!-- for fixing sqeunce jscript error on pages -->
    <span id="sequence"> </span>
  </div>
  <%= javascript_include_tag "http://maps.googleapis.com/maps/api/js?sensor=false" %>
  <%= javascript_include_tag "application" %>

  </body>





  </html>